### PR TITLE
Popup window

### PR DESCRIPTION
**Pull request by nstrvs**
We implement the following features:

- [x] When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
- [x] When the user clicks (or taps) the close (X) button, the popup disappears.
- [x] Implementation in both mobile and desktop screen sizes.
- [x] We stick to the design using the templates in Figma.
- [x] We use a JavaScript array to store all of the information for all projects.

### CODE REVIEW

**Review by mmsesay — CHANGES_REQUESTED** [review]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mmsesay** [comment]
- [ ] Your project is looking good. However, the link to your Github project from the pop-up window is not working as expected. Can you guys please ensure you use the correct path to your Github source code?

**Comment by nstrvs** [comment]
> * [x]  Your project is looking good. However, the link to your Github project from the pop-up window is not working as expected. Can you guys please ensure you use the correct path to your Github source code?

- [x] Fixed
Screenshot from 2022-01-27 11-15-42

**Review by rotimiazeez — APPROVED** [review]
# Hi Team👏, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🎉
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
